Poseidon/Controllers/StatusController.cs
using Kendo.Mvc.UI;
using Poseidon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using System.Net.Mail;
using System.Net.Mime;
using System.IO;
using System.Collections;

namespace Poseidon.Controllers
{
    public class StatusController : Controller
    {
        // GET: Status
        public ActionResult ListStatus()
        {
            return View();
        }

        //DATASOURCE LISTA PARA ADMIN 
        public ActionResult ReadStatus([DataSourceRequest] DataSourceRequest request)
        {
            return GetViewStatus(request);
        }
        private JsonResult GetViewStatus(DataSourceRequest request)
        {
            return Json(GetDataStatus().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetDataStatus()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                         from f in zo.DefaultIfEmpty()
                         where a.status == 1
                         select new
                         {
                             a.logger_id,
                             a.logger_sites_name,
                             a.logger_sms,
                             f.zone_name,
                             a.instalation_type,
                             a.necessary_key,
                             a.contact_detail,
                             a.status

                         };

            return result;
        }


        //DATASOURCE LISTA PARA ADMIN READY
        public ActionResult ReadStatusOther([DataSourceRequest] DataSourceRequest request)
        {

            return GetViewStatusOther(request);
        }
        private JsonResult GetViewStatusOther(DataSourceRequest request)
        {
            return Json(GetDataStatusOther().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetDataStatusOther()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join c in db.User
                           on a.user_instalation equals c.user_id 
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                         from f in zo.DefaultIfEmpty()

                          //from g in zu.DefaultIfEmpty()
                         where a.status == 2 || a.status == 3 || a.status == 4 || a.status == 5 || a.status == 6
                         
                         select new
                         {
                             a.logger_id,
                             a.logger_sites_name,
                             a.logger_sms,
                             f.zone_name,
                             a.instalation_type,
                             a.necessary_key,
                             a.contact_detail,
                             a.status,
                             a.user_instalation_start_date,
                             a.user_instalation_end_date,
                             user_instalation = c.user_name,
                             a.approval_date
                         };
            var result2 = result.OrderByDescending(x => x.status);
            return result2;
        }

        
        //DATASOURCE LISTA PARA THECHNICAL PENDING
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return GetView(request);
        }
        private JsonResult GetView(DataSourceRequest request)
        {
            return Json(GetData().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetData()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                            from f in zo.DefaultIfEmpty()
                            where a.status == 1
                         select new
                         {

                             a.logger_id,
                             a.logger_sites_name,  
                             f.zone_name,
                             a.instalation_type,
                             a.necessary_key,
                             a.contact_detail,
                             a.status

                         };
           
            return result;
        }

        //DATASOURCE LISTA PARA THECHNICAL ReadProgress
        public ActionResult ReadProgress([DataSourceRequest] DataSourceRequest request)
        {
            return GetViewProgress(request);
        }
        private JsonResult GetViewProgress(DataSourceRequest request)
        {
            return Json(GetDataProgress().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetDataProgress()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join c in db.User
                            on a.user_instalation equals c.user_id 
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                         from f in zo.DefaultIfEmpty()
                         
                         where a.status == 2
                         select new
                         {

                             a.logger_id,
                             a.logger_sites_name,
                             a.logger_sms,
                             f.zone_name,
                             user_instalation = c.user_name,
                             a.instalation_type,
                             a.necessary_key,
                             a.user_instalation_start_date,
                             a.contact_detail,
                             a.status
                             
                             //instalador_name = c.user_name

                         };

            return result;
        }


        //DATASOURCE LISTA PARA THECHNICAL READY
        public ActionResult OtherData([DataSourceRequest] DataSourceRequest request)
        {
            return GetView2(request);
        }
        private JsonResult GetView2(DataSourceRequest request)
        {
            return Json(GetData2().ToDataSourceResult(request));
        }

        private IEnumerable<dynamic> GetData2()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join c in db.User
                           on a.user_instalation equals c.user_id //into zu
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                         from f in zo.DefaultIfEmpty()
                        
                        // from g in zu.DefaultIfEmpty()
                         where a.status == 3 || a.status == 4 || a.status == 5 || a.status == 6
                         select new
                         {
                             a.logger_id,
                             a.logger_sites_name,
                             a.logger_sms,
                             f.zone_name,
                             a.instalation_type,
                             a.necessary_key,
                             a.contact_detail,
                             a.status,
                             a.user_instalation_start_date,
                             a.user_instalation_end_date,
                             a.user_instalation,
                             a.approval_date,
                             instalation_user = c.user_name

                         };
            result = result.OrderByDescending(x => x.status);
            return result;
        }




        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Logger lo)
        {

            if (ModelState.IsValid)
            {
                using (var northwind = new poseidon_dbEntities())
                {
                    //Get max ID table loggers
                    var crum = 0;
                    try
                    {
                         crum = northwind.Logger.Max(sd => sd.logger_id);
                    }
                    catch
                    {
                        crum = 0;
                    }

                    int current_id = Convert.ToInt32(crum.ToString());

                    var entity = new Logger
                    {
                        logger_id = current_id+1,
                        logger_sites_name = lo.logger_sites_name,
                      
                        latitude = lo.latitude,
                        longitute = lo.longitute,
                        creation_date = DateTime.Now,
                        creation_user = Convert.ToInt16(Session["USERID"].ToString()),
                        status = 1,
                        zone_id = lo.zone_id,
                        company_id = Convert.ToInt16(lo.company_id)
                        
                        
                    };

                    northwind.Logger.Add(entity);
                    northwind.SaveChanges();
               
                }
                return RedirectToAction("ListStatus");
            }
            else
            {
                return View();
            }
           
        }

        
        public ActionResult PreviewInstalation(string ID)
        {
            char[] delimiter = {','};
            string[] ids = ID.Split(delimiter);
            string[] new_ids = ID.Split(delimiter);
            ID = null;
            if (ids.Count() == 1)

Poseidon/Views/Status/Create.cshtml
@model Poseidon.Models.Logger
@{
    ViewBag.Title = "Create";
}
<link href="@Url.Content("~/Content/Status/Create.css")" rel="stylesheet" type="text/css" />
<h2>Nueva Instalación</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="itemrow">
        <p>
            @Html.Label("Lugar")
            @Html.TextBoxFor(model => model.logger_sites_name, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.logger_sites_name)
        </p>

        <p>
            @Html.Label("COMPANY")
            <div class="editor-field">
                @(Html.Kendo().DropDownListFor(m => m.Company.company_id)
                            .DataTextField("company_name")
                            .DataValueField("company_id")
                            .SelectedIndex(1)
                            
                            .HtmlAttributes(new { style = "width:200px" })
                           .DataSource(source =>
                  {
                      source.Read(read =>
                      {
                          read.Action("GetCompany", "Helper"); //Set the Action and Controller name
                      }); //If true the DataSource will not filter the data on the client.
                  })
                )
            </div>
            @Html.ValidationMessageFor(model => model.logger_sms)
        </p>

        <p>
            @(Html.Kendo().DropDownListFor(m => m.zone_id)
              .DataTextField("zone_name")
              .DataValueField("zone_id")
              .HtmlAttributes(new { style = "width:175px" })
              .OptionLabel("Localidad")
              .DataSource(source =>
                  {
                      source.Read(read =>
                      {
                          read.Action("GetZone", "Helper"); //Set the Action and Controller name
                      }); //If true the DataSource will not filter the data on the client.
                  })
            )
            @Html.ValidationMessageFor(x => x.zone_id)

        </p>


        <p>
            @Html.Label("Latitud")
            @Html.TextBoxFor(model => model.latitude, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.latitude)

            @Html.Label("Longitud")
            @Html.TextBoxFor(model => model.longitute, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.longitute)
        </p>
        <p>
            <input type="submit" value="Crear" class="btn btn-default" width="170" id="btnCreate" />
        </p>

    </div>
    <div class="divmap">
        <p>
            @Html.Label("Inserte dirección para busqueda mas rápida")
            @Html.TextBox("address","", new { style= "width:300px" })
            <button id="pasar">Obtener coordenadas</button>

            <div id="map" style="width: 500px; height: 500px; " />

        </p>
    </div>

    <style>
        .itemrow
        {
            margin-bottom: 10px;
        }

    </style>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" type="text/javascript"></script>

}
<script type="text/javascript">

    var lat = null;
    var lng = null;
    
    var map = null;
    var geocoder = null;
    var marker = null;

    $(document).ready(function () {
        var site = $("#contact_detail").data("TextBox");

        $("#necessary_key").click(function () {
            var $this = $(this);

            if ($this.is(':checked')) {
                $('#contact_detail').removeAttr("disabled");
            } else {
                $('#contact_detail').attr("disabled", "disabled")
            }
        });
      
       
       
        jQuery('#pasar').click(function () {
            codeAddress();
            return false;
        });

        initialize();
        InicialcodeAddress();
    });

    var button = document.getElementById('imageButton');

    function codeAddress() {

        //obtengo la direccion del formulario
        var address = document.getElementById("address").value;
        //hago la llamada al geodecoder
        geocoder.geocode({ 'address': address }, function (results, status) {

            //si el estado de la llamado es OK
            if (status == google.maps.GeocoderStatus.OK) {
                //centro el mapa en las coordenadas obtenidas
                map.setCenter(results[0].geometry.location);
                //coloco el marcador en dichas coordenadas
                marker.setPosition(results[0].geometry.location);
                //actualizo el formulario      
                updatePosition(results[0].geometry.location);

                //Añado un listener para cuando el markador se termine de arrastrar
                //actualize el formulario con las nuevas coordenadas
                google.maps.event.addListener(marker, 'dragend', function () {
                    updatePosition(marker.getPosition());
                });
            } else {
                //si no es OK devuelvo error
                alert("No podemos encontrar la direcci&oacute;n, error: " + status);
            }
        });
    }

    function initialize() {

        geocoder = new google.maps.Geocoder();

        //Si hay valores creamos un objeto Latlng
        
         if(lat == null) {
            var latLng = new google.maps.LatLng(-70.65164270000002, -33.4600405);
        }
         else if (lat != '' && lng != '') {
            var latLng = new google.maps.LatLng(lat, lng);
        }
        else {
            var latLng = new google.maps.LatLng(-70.65164270000002, -33.4600405);
        }
        //Definimos algunas opciones del mapa a crear
        var myOptions = {
            center: latLng,//centro del mapa
            zoom: 5,//zoom del mapa
            mapTypeId: google.maps.MapTypeId.ROADMAP //tipo de mapa, carretera, híbrido,etc
        };
        //creamos el mapa con las opciones anteriores y le pasamos el elemento div
        map = new google.maps.Map(document.getElementById("map"), myOptions);

        //creamos el marcador en el mapa
        marker = new google.maps.Marker({
            map: map,//el mapa creado en el paso anterior
            position: latLng,//objeto con latitud y longitud
            draggable: true //que el marcador se pueda arrastrar
        });

        //función que actualiza los input del formulario con las nuevas latitudes
        //Estos campos suelen ser hidden
        updatePosition(latLng);


    }

    function updatePosition(latLng) {

        jQuery('#latitude').val(latLng.lat());
        jQuery('#longitute').val(latLng.lng());

    }

    function InicialcodeAddress() {

        //obtengo la direccion del formulario
        var address = "Nataniel cox";
        //hago la llamada al geodecoder
        geocoder.geocode({ 'address': address }, function (results, status) {

            //si el estado de la llamado es OK
            if (status == google.maps.GeocoderStatus.OK) {
                //centro el mapa en las coordenadas obtenidas
                map.setCenter(results[0].geometry.location);
                //coloco el marcador en dichas coordenadas
                marker.setPosition(results[0].geometry.location);
                //actualizo el formulario      
                updatePosition(results[0].geometry.location);

                //Añado un listener para cuando el markador se termine de arrastrar
                //actualize el formulario con las nuevas coordenadas
                google.maps.event.addListener(marker, 'dragend', function () {
                    updatePosition(marker.getPosition());
                });
            } else {
                //si no es OK devuelvo error
                alert("No podemos encontrar la direcci&oacute;n, error: " + status);
            }
        });
    }
  
    

</script>

@*<div style='padding:10px 0'>
    <table style='width:100%' cellpadding='0' cellspacing='0'>
    <tbody>
        <tr>
        <td>
            <a href='http://www.dnk-water.com' target='_blank'>
                <img src='http://158.85.25.234/Poseidon/Content//images/dnk_logo.png' style='border:0;width:150px; height:100px' class='CToWUd'>
            </a>
         </td>
        </tr>
     </tbody>
    </table>
</div>



<div style='background-color:#4285f4;color:white;font:20px arial,normal;padding:23px 20px'>Hay una publicación que quizá no hayas leído</div>
<div style='background-color:#f5f5f5;margin-bottom:15px;padding:20px 30px 20px 30px'>
    <div style='max-width:520px'>
        <div style='background-color:white;border:1px solid #dadada;border-bottom-width:2px;border-top:none'>
            <div style='padding:14px'>
                <table style='width:100%' cellpadding='0' cellspacing='0'>
                    <tbody>
                        <tr>
                            <td>
                                <h3>Estimado(a)+to_name,</h3>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td style='width:90px'>Ubicación</td>
                            <td>:</td>
                            <td style='padding-left:14px'>
                                
                            </td>
                        </tr>
                        <tr>
                            <td style='width:90px'>Localidad</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:90px'>SMS</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:90px'>CSQ</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                    </tbody>
                </table>

                <br />
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <h4>Donde el equipo obtuvo el siguiente resultado</h4>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <table style='width:100%' cellpadding='0' cellspacing='0'>
                    <tbody>
                        <tr>
                            <td style='width:175px'>Fecha inicio instalación</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:175px'>Fecha termino instalación</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:175px'>Instalado por</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:175px'>Comentario instalación</td>
                            <td>:</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                        <tr>
                            <td style='width:175px'>Imagen de instalación</td>
                            <td style='padding-left:14px'></td>
                        </tr>
                    </tbody>
                </table>
            </div>
          
        </div>
    </div>
</div>*@

Poseidon/Views/Status/Edit.cshtml
@model Poseidon.Models.Logger
@{
    ViewBag.Title = "Detalle";
}
<link href="@Url.Content("~/Content/Status/Create.css")" rel="stylesheet" type="text/css" />
<h2>Nueva Instalación</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="itemrow">
        <p>
            @Html.Label("Lugar")
            @Html.TextBoxFor(model => model.logger_sites_name, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.logger_sites_name)
        </p>

        <p>
            @Html.Label("SMS")
            @Html.TextBoxFor(model => model.logger_sms, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.logger_sms)
        </p>

        <p>
            @(Html.Kendo().DropDownListFor(m => m.zone_id)
              .DataTextField("zone_name")
              .DataValueField("zone_id")
              .HtmlAttributes(new { style = "width:175px" })
              .OptionLabel("Zone")
              .DataSource(source =>
                  {
                      source.Read(read =>
                      {
                          read.Action("GetZone", "Helper"); //Set the Action and Controller name
                      }); //If true the DataSource will not filter the data on the client.
                  })
            )
            @Html.ValidationMessageFor(x => x.zone_id)

        </p>

        <p>
            @Html.Label("Necesario llave")
            @(Html.CheckBoxFor(model => model.necessary_key.HasValue)
            )
        </p>

        <p>
            @Html.Label("Detalle Contacto llave")
            @Html.TextBoxFor(model => model.contact_detail, new { @class = "form-control", style = "width:170px", @disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.contact_detail)
        </p>

        <p>
            @Html.Label("¿Se dispone con llave de bola con salida media?")
            @(Html.CheckBoxFor(model => model.key_ball.HasValue, new { @checked = true }))

        </p>

        <p>
            @Html.Label("Latitud")
            @Html.TextBoxFor(model => model.latitude, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.latitude)

            @Html.Label("Longitud")
            @Html.TextBoxFor(model => model.longitute, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.longitute)
        </p>
        <p>
            <input type="submit" value="Guardar" class="btn btn-default" width="170" id="btnCreate" />
            <input type="button" value="Volver" class="btn btn-default" width="170" id="btnBack" onclick="location.href='@Url.Action("ListStatus", "Status")' " />
        </p>

    </div>
    <div class="divmap">
        <p>
            @Html.Label("Inserte dirección para busqueda mas rápida")
            @Html.TextBox("address", "", new { style = "width:300px" })
            <button id="pasar">Obtener coordenadas</button>

            <div id="map" style="width: 500px; height: 500px; " />

        </p>
    </div>

    <style>
        .itemrow {
            margin-bottom: 10px;
        }
    </style>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" type="text/javascript"></script>

}
<script type="text/javascript">

    var lat = $("#latitude").val();
    var lng = $("#longitute").val();
    var map = null;
    var geocoder = null;
    var marker = null;

    $(document).ready(function () {
      

        var site = $("#contact_detail").data("TextBox");

        $("#necessary_key").click(function () {
            var $this = $(this);

            if ($this.is(':checked')) {
                $('#contact_detail').removeAttr("disabled");
            } else {
                $('#contact_detail').attr("disabled", "disabled")
            }
        });



        jQuery('#pasar').click(function () {
            codeAddress();
            return false;
        });

        initialize();
        InicialcodeAddress();
    });

    var button = document.getElementById('imageButton');

    function codeAddress() {

        //obtengo la direccion del formulario
        var address = document.getElementById("address").value;
        //hago la llamada al geodecoder
        geocoder.geocode({ 'address': address }, function (results, status) {

            //si el estado de la llamado es OK
            if (status == google.maps.GeocoderStatus.OK) {
                //centro el mapa en las coordenadas obtenidas
                map.setCenter(results[0].geometry.location);
                //coloco el marcador en dichas coordenadas
                marker.setPosition(results[0].geometry.location);
                //actualizo el formulario
                updatePosition(results[0].geometry.location);

                //Añado un listener para cuando el markador se termine de arrastrar
                //actualize el formulario con las nuevas coordenadas
                google.maps.event.addListener(marker, 'dragend', function () {
                    updatePosition(marker.getPosition());
                });
            } else {
                //si no es OK devuelvo error
                alert("No podemos encontrar la direcci&oacute;n, error: " + status);
            }
        });
    }

    function initialize() {

        geocoder = new google.maps.Geocoder();

        //Si hay valores creamos un objeto Latlng

         if(lat == null) {
            var latLng = new google.maps.LatLng(-70.65164270000002, -33.4600405);
        }
         else if (lat != '' && lng != '') {
            var latLng = new google.maps.LatLng(lat, lng);
        }
        else {
            var latLng = new google.maps.LatLng(-70.65164270000002, -33.4600405);
        }
        //Definimos algunas opciones del mapa a crear
        var myOptions = {
            center: latLng,//centro del mapa
            zoom: 5,//zoom del mapa
            mapTypeId: google.maps.MapTypeId.ROADMAP //tipo de mapa, carretera, híbrido,etc
        };
        //creamos el mapa con las opciones anteriores y le pasamos el elemento div
        map = new google.maps.Map(document.getElementById("map"), myOptions);

        //creamos el marcador en el mapa
        marker = new google.maps.Marker({
            map: map,//el mapa creado en el paso anterior
            position: latLng,//objeto con latitud y longitud
            draggable: true //que el marcador se pueda arrastrar
        });

        //función que actualiza los input del formulario con las nuevas latitudes
        //Estos campos suelen ser hidden
        updatePosition(latLng);


    }

    function updatePosition(latLng) {

        jQuery('#latitude').val(latLng.lat());
        jQuery('#longitute').val(latLng.lng());

    }

    function InicialcodeAddress() {

        //obtengo la direccion del formulario
        var address = null;
        //hago la llamada al geodecoder
        geocoder.geocode({ 'address': address }, function (results, status) {

            //si el estado de la llamado es OK
            if (status == google.maps.GeocoderStatus.OK) {
                //centro el mapa en las coordenadas obtenidas
                map.setCenter(results[0].geometry.location);
                //coloco el marcador en dichas coordenadas
                marker.setPosition(results[0].geometry.location);
                //actualizo el formulario
                updatePosition(results[0].geometry.location);

                //Añado un listener para cuando el markador se termine de arrastrar
                //actualize el formulario con las nuevas coordenadas
                google.maps.event.addListener(marker, 'dragend', function () {
                    updatePosition(marker.getPosition());
                });
            } else {
                //si no es OK devuelvo error
                alert("No podemos encontrar la direcci&oacute;n, error: " + status);
            }
        });
    }


</script>

Poseidon/Views/Status/PreviewInstalation.cshtml
@model Poseidon.Models.Logger
@{
    ViewBag.Title = "PreviewInstalation";
}

<h2>Preview Instalation</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    <p>
        @Html.HiddenFor(model => model.logger_id)
        @Html.Label("Logger Seleccionado")
        @Html.TextBoxFor(model => model.logger_sites_name, new { @class = "form-control", style = "width:190px" })
        @Html.ValidationMessageFor(model => model.logger_sms)
    </p>

    <p>
        @Html.Label("Fecha Instalación")
         @(Html.Kendo().DateTimePickerFor(model => model.user_instalation_start_date)
          .Value(DateTime.Now.AddDays(-1))
          .Format("yyyy-MM-dd HH:mm")
          .HtmlAttributes(new { style = "width: 200px" })
          .Min(DateTime.Today)
         )
        @Html.ValidationMessageFor(model => model.user_instalation_start_date, String.Empty, new { @class = "help-inline", @style = "color:red" })

    </p>

    <p>
        @Html.Label("Fecha término")
        @(Html.Kendo().DateTimePickerFor(model => model.user_instalation_end_date)
          .Value(DateTime.Now.AddDays(1))
          .Format("yyyy-MM-dd HH:mm")
          .Min(DateTime.Today.AddDays(-1))
        )
        @Html.ValidationMessageFor(model => model.user_instalation_end_date, String.Empty, new { @class = "help-inline", @style = "color:red" })

      
    </p>

    <p>
        <input type="submit" value="Agendar" class="btn btn-default" width="170" id="btnCreate" />
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}