Poseidon/Controllers/MapController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Poseidon.Models;

namespace Poseidon.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        public ActionResult LoggerList()
        {
            return View();
        }

        //DATASOURCE LISTA PARA ADMIN 
        public ActionResult ReadLogger([DataSourceRequest] DataSourceRequest request)
        {
            return GetViewStatus(request);
        }
        private JsonResult GetViewStatus(DataSourceRequest request)
        {
            return Json(GetDataStatus().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetDataStatus()
        {
            poseidon_dbEntities db = new poseidon_dbEntities();

            var result = from a in db.Logger
                         join b in db.zones
                            on a.zone_id equals b.zone_id into zo
                         from f in zo.DefaultIfEmpty()
                         join c in db.User
                            on a.user_instalation equals c.user_id into zu
                         from g in zu.DefaultIfEmpty()
                         join d in db.Company
                            on a.company_id equals d.company_id
                         select new
                         {
                             a.logger_id,
                             a.logger_sites_name,
                             f.zone_name,
                             a.status,
                             a.user_instalation_start_date,
                             a.approval_date,
                             user_instalation = g.user_name,
                             company_id = d.company_name,

                         };

            return result;
        }
    }
}

Poseidon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title - DNK WATER</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    	<link href="@Url.Content("~/Content/kendo/2014.3.1119/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.3.1119/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.3.1119/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.3.1119/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.3.1119/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2014.3.1119/jquery.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2014.3.1119/jszip.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2014.3.1119/kendo.all.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2014.3.1119/kendo.aspnetmvc.min.js")"></script>
        <script src="@Url.Content("~/Scripts/kendo/2014.3.1119/kendo.validator.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.jqprint.0.3.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
    <body>
        <style type="text/css" media="screen">
            .chileFlag {
                background-image: url('../Content/images/Chile.png');
                width: 32px;
                height: 32px;
                float:left;
                background-position: initial;
            }
            .dnkFlag {
                background-image: url('../Content/images/dnk_logo.png');
                background-size: 60px 40px;
                width: 60px;
                height: 40px;
                float: left;
                background-repeat: no-repeat;
                margin-left:5px;
            }         
        </style>
        <header>
            <div class="content-wrapper">
                
                <div class="dnkFlag"></div>
                <div class="float-left">
                    @*<p class="site-title">@Html.ActionLink("Poseidon Controller", "Index", "Home")</p>*@
                   
                    @if (User.Identity.IsAuthenticated)
                    {
                    <ul id="menu">
                        <li>@Html.ActionLink("Listado", "ListCondition", "Home")</li>

                        @*if(User.IsInRole("admin"))*@
                        
                        @*<li>@Html.ActionLink("Mapa", "LoggerList", "Map")</li>*@
                        
                    </ul>

                    }
</div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                          
                           @if (User.Identity.IsAuthenticated)
                            {
                            <li>@Html.ActionLink("Salir", "LogOut", "Home")</li>
                           }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Poseidon Controller - DNK Water</p>
                    <div class="chileFlag"></div>
                </div>
            </div>
            @RenderSection("scripts", required: false)
        </footer>

        @section Scripts {
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        }
    </body>
</html>